Import pandas

In [1]:
import pandas as pd

import your data

In [3]:
kick_starter = pd.read_csv("ks-projects-201801.csv")
kick_starter

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378656,999976400,ChknTruk Nationwide Charity Drive 2014 (Canceled),Documentary,Film & Video,USD,2014-10-17,50000.0,2014-09-17 02:35:30,25.0,canceled,1,US,25.0,25.0,50000.00
378657,999977640,The Tribe,Narrative Film,Film & Video,USD,2011-07-19,1500.0,2011-06-22 03:35:14,155.0,failed,5,US,155.0,155.0,1500.00
378658,999986353,Walls of Remedy- New lesbian Romantic Comedy f...,Narrative Film,Film & Video,USD,2010-08-16,15000.0,2010-07-01 19:40:30,20.0,failed,1,US,20.0,20.0,15000.00
378659,999987933,BioDefense Education Kit,Technology,Technology,USD,2016-02-13,15000.0,2016-01-13 18:13:53,200.0,failed,6,US,200.0,200.0,15000.00
378660,999988282,Nou Renmen Ayiti! We Love Haiti!,Performance Art,Art,USD,2011-08-16,2000.0,2011-07-19 09:07:47,524.0,failed,17,US,524.0,524.0,2000.00

### Converting Columns to upper case 

- Lets convert the columns to uppercase. 
- For this we will use the `.upper()` method
- To do this we need to address only the columns 
- Start with `kick_starter.columns =`  
- Did you get an error? 
- Hints below if needed

In [4]:
# your code here 
kick_starter.columns = kick_starter.upper()

AttributeError: 'DataFrame' object has no attribute 'upper'

### Did you get an error? 

The reason we can't simply use `.upper()` on the DataFrame's column names is that 
- .upper() is a method designed for strings 
- while DataFrame.columns is an Index object (a collection of strings). 
  
  
#### Let's break it down:

Why Not .upper() Directly?
Data Type Difference:
- `df.columns` returns an Index object, not a single string. 
- The `.upper()` method only works on individual strings 
- columns are stored in a list-like structure (Index).

#### Broadcasting Needed:
To apply `.upper()` to each column name, we need to broadcast it over all the column names. <br> 
Pandas provides the `.str` accessor to handle such operations efficiently.

#### Why Use `.str.upper()`?
The `.str` accessor in pandas allows us to apply string methods like `.upper()` to each element in the Index object.
`.str.upper()` ensures that the transformation applies to all column names in one step, treating them as individual strings.

### Converting Columns to title case 

- Start the same way we did above
- Rather than `.upper()` we will use `.title()`
- What did that do to the columns?

In [8]:
# your code here 
kick_starter.columns = kick_starter.columns.str.title()
kick_starter

,Id,Name,Category,Main_Category,Currency,Deadline,Goal,Launched,Pledged,State,Backers,Country,Usd Pledged,Usd_Pledged_Real,Usd_Goal_Real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378656,999976400,ChknTruk Nationwide Charity Drive 2014 (Canceled),Documentary,Film & Video,USD,2014-10-17,50000.0,2014-09-17 02:35:30,25.0,canceled,1,US,25.0,25.0,50000.00
378657,999977640,The Tribe,Narrative Film,Film & Video,USD,2011-07-19,1500.0,2011-06-22 03:35:14,155.0,failed,5,US,155.0,155.0,1500.00
378658,999986353,Walls of Remedy- New lesbian Romantic Comedy f...,Narrative Film,Film & Video,USD,2010-08-16,15000.0,2010-07-01 19:40:30,20.0,failed,1,US,20.0,20.0,15000.00
378659,999987933,BioDefense Education Kit,Technology,Technology,USD,2016-02-13,15000.0,2016-01-13 18:13:53,200.0,failed,6,US,200.0,200.0,15000.00
378660,999988282,Nou Renmen Ayiti! We Love Haiti!,Performance Art,Art,USD,2011-08-16,2000.0,2011-07-19 09:07:47,524.0,failed,17,US,524.0,524.0,2000.00

## Other Similar Methods  

1. `str.title()`
Capitalizes the first letter of each word in the column names.

    ```js
    kick_starter.columns = kick_starter.columns.str.title()
    ```
    
        Example:
        "project_name" becomes "Project_Name"

2. `str.lower()`
Converts all column names to lowercase.

    ```js
    kick_starter.columns = kick_starter.columns.str.lower()
    ```

        Example:
        "Project_Name" becomes "project_name"

3. `str.upper()`
Converts all column names to uppercase.

    ```js
    kick_starter.columns = kick_starter.columns.str.upper()
    ```

        Example:
        "Project_Name" becomes "PROJECT_NAME"

4. `str.strip()`
Removes leading and trailing whitespace from column names.

    ```js
    kick_starter.columns = kick_starter.columns.str.strip()
    ```

        Example:
        " Project_Name " becomes "Project_Name"

5. `str.replace()`
Replaces a specific substring in the column names with another string.

    ```js
    kick_starter.columns = kick_starter.columns.str.replace('_', ' ')
    ```

        Example:
        "Project_Name" becomes "Project Name"

6. `str.contains()` (for filtering columns)
(Not for renaming, but useful for selecting columns.)
Checks if column names contain a specific substring.

    ```js
    columns_with_name = kick_starter.columns[kick_starter.columns.str.contains('name')]
    print(columns_with_name)
    ```

        Example:
        Returns column names that include "name".

7. str.startswith() / str.endswith()
Filters columns based on their starting or ending substring.

    ```js
    // Columns that start with 'proj'
    columns_starting_with_proj = kick_starter.columns[kick_starter.columns.str.startswith('proj')]

    // Columns that end with 'name'
    columns_ending_with_name = kick_starter.columns[kick_starter.columns.str.endswith('name')]
    ```

8. str.capitalize()
Capitalizes the first letter of the first word in each column name.

    ```js
    kick_starter.columns = kick_starter.columns.str.capitalize()
    ```

        Example:
        "project_name" becomes "Project_name"

9. `str.replace()` with regex
You can also use regex=True for complex replacements.

    ```js
    kick_starter.columns = kick_starter.columns.str.replace(r'\s+', '_', regex=True)
    ```

        Example:
        Replaces spaces with underscores.

10. Combining Methods
You can chain multiple methods together.

    ```js
    kick_starter.columns = (
        kick_starter.columns
        .str.strip()
        .str.lower()
        .str.replace(' ', '_')
    )
    ```

        Example:
        " Project Name " becomes "project_name"

## Remove White Space and Underscores 

Here we will chain some methods together to accomplish the task.  
Our goal is to remove any white space that might be before or after our column names.   
Then we will remove underscore and replace them with a space. 

- Start with `kick_starter.columns =` 
- Then strip the white space 
- Then handle replacing the underscore 
- This should all be ones line of code

In [13]:
# your code here 
kick_starter.columns = kick_starter.columns.str.strip().str.replace('_', ' ')
kick_starter

,Id,Name,Category,Main Category,Currency,Deadline,Goal,Launched,Pledged,State,Backers,Country,Usd Pledged,Usd Pledged Real,Usd Goal Real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378656,999976400,ChknTruk Nationwide Charity Drive 2014 (Canceled),Documentary,Film & Video,USD,2014-10-17,50000.0,2014-09-17 02:35:30,25.0,canceled,1,US,25.0,25.0,50000.00
378657,999977640,The Tribe,Narrative Film,Film & Video,USD,2011-07-19,1500.0,2011-06-22 03:35:14,155.0,failed,5,US,155.0,155.0,1500.00
378658,999986353,Walls of Remedy- New lesbian Romantic Comedy f...,Narrative Film,Film & Video,USD,2010-08-16,15000.0,2010-07-01 19:40:30,20.0,failed,1,US,20.0,20.0,15000.00
378659,999987933,BioDefense Education Kit,Technology,Technology,USD,2016-02-13,15000.0,2016-01-13 18:13:53,200.0,failed,6,US,200.0,200.0,15000.00
378660,999988282,Nou Renmen Ayiti! We Love Haiti!,Performance Art,Art,USD,2011-08-16,2000.0,2011-07-19 09:07:47,524.0,failed,17,US,524.0,524.0,2000.00

# Dropping columns We Don't Need 

### Why Do We Drop Columns in Data Analytics?
- **Reduce Noise:** Irrelevant columns can obscure important patterns.

- **Improve Efficiency:** Fewer columns mean faster computations.

- **Prevent Overfitting:** Reducing irrelevant features helps models generalize better.

- **Enhance Clarity:** Simplifies data interpretation and reporting.

- **Ensure Privacy:** Removes sensitive or personally identifiable information (PII).

- **Avoid Redundancy:** Drops duplicate or highly correlated features.

- **Focus on Goals:** Keeps only columns relevant to the analysis objective.

With the above in mind let's pick some columns to drop. First we will need to identify some questions and be sure we don't drop columns we don't need. Also we can just infer we may not need certain columns. An example being "Id". We have no other data to reference this column with so we can remove it. 

Things we want to accomplish with our data:
- Filter to US only in Country 
- Goal status for plot 
- What category has the most backers. 
- What has the highest backing amount

With the above questions we can determine columns to remove. 
- 'Id' : We can remove this because we can't reference this to anything with our limited data 
- 'Name' : We will want to keep this so we know what project is what 
- 'Category' : We will primarily look at Main Category but this could be helpful
- 'Main Category' : We have a goal directly related to this column
- 'Currency' : We have a goal related to Currency so we will keep this 
- 'Deadline' : We wont need this column as we have no goals related to this column 
- 'Goal' : we will keep this as and Usd Goal Real
- 'Launched' : We wont need this column as we have no goals related to this column 
- 'Pledged' : We will keep this and Usd Pledged Real
- 'State' :  keep ...
- 'Backers' : keep ...
- 'Country' : keep ...
- 'Usd Pledged' : keep  ...
- 'Usd Pledged Real' : keep ...
- 'Usd Goal Real' : keep ...

Using the list above lest use the `.drop()` method to remove the columns

In [18]:
# your code here
kick_starter_cleaned = kick_starter.drop(['Id', 'Deadline', 'Launched'], axis=1)
kick_starter_cleaned

,Name,Category,Main Category,Currency,Goal,Pledged,State,Backers,Country,Usd Pledged,Usd Pledged Real,Usd Goal Real
0,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,1000.0,0.0,failed,0,GB,0.0,0.0,1533.95
1,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,30000.0,2421.0,failed,15,US,100.0,2421.0,30000.00
2,Where is Hank?,Narrative Film,Film & Video,USD,45000.0,220.0,failed,3,US,220.0,220.0,45000.00
3,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,5000.0,1.0,failed,1,US,1.0,1.0,5000.00
4,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,19500.0,1283.0,canceled,14,US,1283.0,1283.0,19500.00
...,...,...,...,...,...,...,...,...,...,...,...,...
378656,ChknTruk Nationwide Charity Drive 2014 (Canceled),Documentary,Film & Video,USD,50000.0,25.0,canceled,1,US,25.0,25.0,50000.00
378657,The Tribe,Narrative Film,Film & Video,USD,1500.0,155.0,failed,5,US,155.0,155.0,1500.00
378658,Walls of Remedy- New lesbian Romantic Comedy f...,Narrative Film,Film & Video,USD,15000.0,20.0,failed,1,US,20.0,20.0,15000.00
378659,BioDefense Education Kit,Technology,Technology,USD,15000.0,200.0,failed,6,US,200.0,200.0,15000.00
378660,Nou Renmen Ayiti! We Love Haiti!,Performance Art,Art,USD,2000.0,524.0,failed,17,US,524.0,524.0,2000.00

# Address Nulls Remove vs 0 vs Back Fill ect.

### 1. Remove Rows with Null Values
Use Case: When missing data is sparse or not crucial to the analysis.

```python
# Drop rows with any NaN values
kick_starter_cleaned = kick_starter.dropna()

# Drop rows where specific columns have NaN
kick_starter_cleaned = kick_starter.dropna(subset=['Column1', 'Column2'])
```

Explanation:
- dropna() removes rows where any column has NaN.
- subset targets specific columns only.

### 2. Fill Nulls with Zero
Use Case: When missing values represent quantities like counts or amounts.

```python
# Fill all NaN values with 0
kick_starter_filled = kick_starter.fillna(0)
```

Explanation:
- Filling with 0 ensures calculations like sums are not affected by missing data.

### 3. Fill Nulls with a Specific Value
Use Case: When missing data should default to a constant like "Unknown."

```python
# Fill NaN in a specific column with 'Unknown'
kick_starter['Category'] = kick_starter['Category'].fillna('Unknown')
```

Explanation:
- This is useful for categorical columns where missing data can be treated as a new category.

### 4. Forward Fill (Use Previous Value)
Use Case: For time-series data or when prior values can logically fill gaps.

```python
# Fill NaN using the previous value in the same column
kick_starter_ffill = kick_starter.fillna(method='ffill')
```

Explanation:
- Uses the last valid value to fill the NaN, ideal for propagating information in sequences.


### 5. Backward Fill (Use Next Value)
Use Case: Similar to forward fill, but uses subsequent values instead.

```python
# Fill NaN using the next value in the same column
kick_starter_bfill = kick_starter.fillna(method='bfill')
```

Explanation:
- Backfills using the next available value, ideal when later data can logically fill gaps.

### 6. Fill with Column Mean/Median/Mode
Use Case: For numerical data where imputing missing values based on the distribution is valid.

```python
# Fill NaN with the column mean
kick_starter['Amount'] = kick_starter['Amount'].fillna(kick_starter['Amount'].mean())

# Fill NaN with the column median
kick_starter['Amount'] = kick_starter['Amount'].fillna(kick_starter['Amount'].median())

# Fill NaN with the column mode (most frequent value)
kick_starter['Category'] = kick_starter['Category'].fillna(kick_starter['Category'].mode()[0])
```

Explanation:
- mean and median are for numerical data.
- mode is best for categorical data.

### 7. Interpolate Missing Values
Use Case: For continuous data where missing values can be estimated.

```python
# Linear interpolation
kick_starter_interpolated = kick_starter.interpolate(method='linear')
```

Explanation:
- Interpolates missing values based on surrounding data points. Useful for numerical and time-series data.

We are just going to drop all missing values to keep it 
- use the `.dropna()` method.

In [19]:
# your code here
kick_starter_clean = kick_starter.dropna()
kick_starter_clean

,Id,Name,Category,Main Category,Currency,Deadline,Goal,Launched,Pledged,State,Backers,Country,Usd Pledged,Usd Pledged Real,Usd Goal Real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378656,999976400,ChknTruk Nationwide Charity Drive 2014 (Canceled),Documentary,Film & Video,USD,2014-10-17,50000.0,2014-09-17 02:35:30,25.0,canceled,1,US,25.0,25.0,50000.00
378657,999977640,The Tribe,Narrative Film,Film & Video,USD,2011-07-19,1500.0,2011-06-22 03:35:14,155.0,failed,5,US,155.0,155.0,1500.00
378658,999986353,Walls of Remedy- New lesbian Romantic Comedy f...,Narrative Film,Film & Video,USD,2010-08-16,15000.0,2010-07-01 19:40:30,20.0,failed,1,US,20.0,20.0,15000.00
378659,999987933,BioDefense Education Kit,Technology,Technology,USD,2016-02-13,15000.0,2016-01-13 18:13:53,200.0,failed,6,US,200.0,200.0,15000.00
378660,999988282,Nou Renmen Ayiti! We Love Haiti!,Performance Art,Art,USD,2011-08-16,2000.0,2011-07-19 09:07:47,524.0,failed,17,US,524.0,524.0,2000.00

# Filter the DataFrame to Include Only US-based Records

- **Step 1:** 
  - Identify the column that contains country information.

- **Step 2:** 
  - Understand the structure of the DataFrame.
  - You will need to filter the rows where the value in the "Country" column is equal to "US" (the United States).

- **Step 3:** 
  - Use a filtering condition.
  - You'll want to create a condition that checks if the "Country" column contains the value "US". This will result in a boolean series (True or False for each row).

- **Step 4:** 
  - Apply the condition to the DataFrame.
  - Once you have the condition, apply it to the DataFrame to return only the rows where the condition is true.

- **Step 5:** 
  - Assign the result back to the DataFrame.
  - After filtering, ensure you store the filtered DataFrame back into the original variable to update it.

- **Tips:**
  - Remember, the condition should be based on the value of the "Country" column.
  - Be careful with case sensitivity (e.g., "US" vs "us").
  - This will be one line of code

In [23]:
# your code here
kick_starter_us = kick_starter['Country'].str.contains('US')
kick_starter_us

0         False
1          True
2          True
3          True
4          True
          ...
378656     True
378657     True
378658     True
378659     True
378660     True
Name: Country, Length: 378661, dtype: bool

# Calculate Total, Mean, and Median of Backers

**Step 1:** Identify the column that contains the number of backers.

**Step 2:** Calculate the total number of backers.

**Step 3:** Calculate the mean (average) number of backers and round 2 places.

**Step 4:** Calculate the median number of backers.

**Step 5:** Display the results using print().

**Step 6:** Ensure formatting of your print statement more readable.

In [24]:
# your code here
pd.set_option('display.float_format', '{:.2f}'.format)
kick_starter_backers = kick_starter['Backers'].sum
print(kick_starter_backers)
kick_starter_backers_avg = kick_starter['Backers'].mean()
print(kick_starter_backers_avg)
kick_starter_backers_median = kick_starter['Backers'].median()
print(kick_starter_backers_median)

<bound method Series.sum of 0          0
1         15
2          3
3          1
4         14
          ..
378656     1
378657     5
378658     1
378659     6
378660    17
Name: Backers, Length: 378661, dtype: int64>
105.61747578969052
12.0

# Find the Category with the Most Backers

**Step 1:** Identify the columns for "Backers" and "Category".

**Step 2:** Group the data by the "Category" column.
- Use the `groupby()` function to group the data by the "Category" column, which will allow you to perform operations on each category.

**Step 3:** Sum the backers for each category.
- After grouping, apply the `sum()` function to get the total number of backers for each category.

**Step 4:** Find the category with the maximum total number of backers.
- Use the `idxmax()` function to find the category that has the highest sum of backers.

**Step 5:** Display the result.
Print out the category with the most backers and the number of backers it has.

In [28]:
# your code here
category_backers = ['Backers', 'Category']
grouped_kick_starter = kick_starter[category_backers].groupby('Category').sum()
print(grouped_kick_starter)

highest_backers = grouped_kick_starter.idxmax()
print(highest_backers)

             Backers
Category
3D Printing   158779
Academic       37751
Accessories   256036
Action         34708
Animals        10748
...              ...
Woodworking    22612
Workshops       3422
World Music   113403
Young Adult    15927
Zines          21725

[159 rows x 1 columns]
Backers    Product Design
dtype: object

### Sort the Categories by Number of Backers in Descending Order

**Step 1:** Using the `category_backers` variable.
This variable contains the total number of backers for each category, which was previously calculated by grouping the data and summing the backers for each category.

**Step 2:** Use the `sort_values()` function to sort the `category_backers`.
The sort_values() function is used to sort the values in a Series or DataFrame. You need to specify the ascending parameter to control the order.

**Step 3:** Set `ascending=False` to sort in descending order.
By setting ascending=False, you will sort the data so that the category with the most backers appears first.

**Step 4:** Assign the sorted result back to the `category_backers` variable.
Ensure that the sorted result is saved to the same variable so it updates with the new order.

**Step 5:** Print the top 10 categories.

In [36]:
# your code here
category_backers = kick_starter.sort_values(category_backers, ascending=False)
print(category_backers.head())

KeyError:                 Id                                               Name  \
187652  1955357092                                  Exploding Kittens
75900   1386523707                      Fidget Cube: A Vinyl Desk Toy
292244   557230947  Bring Reading Rainbow Back for Every Child, Ev...
148585  1755266685                    The Veronica Mars Movie Project
182657  1929840910                              Double Fine Adventure
...            ...                                                ...
358401   895847309                             Pato's Online Emporium
362409   916526958                            3d Printers for Schools
368644   948183726                                             Forg3X
375683   984716122                                    #TVATOURUSA2015
378643   999931480                     Google Glass Shield (Canceled)

              Category Main Category Currency    Deadline       Goal  \
187652  Tabletop Games         Games      USD  2015-02-20   10000.00
75900   Product Design        Design      USD  2016-10-20   15000.00
292244             Web    Technology      USD  2014-07-02 1000000.00
148585  Narrative Film  Film & Video      USD  2013-04-13 2000000.00
182657     Video Games         Games      USD  2012-03-14  400000.00
...                ...           ...      ...         ...        ...
358401     3D Printing    Technology      USD  2015-04-24    3000.00
362409     3D Printing    Technology      USD  2015-05-29    1500.00
368644     3D Printing    Technology      AUD  2014-08-30   15000.00
375683     3D Printing    Technology      CAD  2015-06-20   22000.00
378643     3D Printing    Technology      USD  2014-05-26    6500.00

                   Launched    Pledged       State  Backers Country  \
187652  2015-01-20 19:00:19 8782571.99  successful   219382      US
75900   2016-08-30 22:02:09 6465690.30  successful   154926      US
292244  2014-05-28 15:05:45 5408916.95  successful   105857      US
148585  2013-03-13 15:42:22 5702153.38  successful    91585      US
182657  2012-02-09 02:52:52 3336371.92  successful    87142      US
...                     ...        ...         ...      ...     ...
358401  2015-03-14 06:05:14       0.00      failed        0      US
362409  2015-04-24 04:29:21       0.00      failed        0      US
368644  2014-07-31 11:49:42       0.00      failed        0      AU
375683  2015-05-21 01:45:22       0.00      failed        0      CA
378643  2014-05-05 20:22:45       0.00    canceled        0      US

        Usd Pledged  Usd Pledged Real  Usd Goal Real
187652   8782571.99        8782571.99       10000.00
75900      13770.00        6465690.30       15000.00
292244   5408916.95        5408916.95     1000000.00
148585   5702153.38        5702153.38     2000000.00
182657   3336371.92        3336371.92      400000.00
...             ...               ...            ...
358401         0.00              0.00        3000.00
362409         0.00              0.00        1500.00
368644         0.00              0.00       14047.57
375683         0.00              0.00       17792.16
378643         0.00              0.00        6500.00

[378661 rows x 15 columns]

Print the last 10 categories.

In [37]:
# your code here
print(category_backers.tail())

               Id                            Name     Category Main Category  \
358401  895847309          Pato's Online Emporium  3D Printing    Technology
362409  916526958         3d Printers for Schools  3D Printing    Technology
368644  948183726                          Forg3X  3D Printing    Technology
375683  984716122                 #TVATOURUSA2015  3D Printing    Technology
378643  999931480  Google Glass Shield (Canceled)  3D Printing    Technology

       Currency    Deadline     Goal             Launched  Pledged     State  \
358401      USD  2015-04-24  3000.00  2015-03-14 06:05:14     0.00    failed
362409      USD  2015-05-29  1500.00  2015-04-24 04:29:21     0.00    failed
368644      AUD  2014-08-30 15000.00  2014-07-31 11:49:42     0.00    failed
375683      CAD  2015-06-20 22000.00  2015-05-21 01:45:22     0.00    failed
378643      USD  2014-05-26  6500.00  2014-05-05 20:22:45     0.00  canceled

        Backers Country  Usd Pledged  Usd Pledged Real  Usd Goal Real
358401        0      US         0.00              0.00        3000.00
362409        0      US         0.00              0.00        1500.00
368644        0      AU         0.00              0.00       14047.57
375683        0      CA         0.00              0.00       17792.16
378643        0      US         0.00              0.00        6500.00

# More complex groupby and plots

This code will only work if install matplotlib and have done your code correct as it uses your variables column names.

In [ ]:
# Filter the DataFrame for successful projects
filtered_data = kick_starter[kick_starter['State'] == 'successful']

# Group by Category and State and sum the specified columns
top_ten_cats = filtered_data.groupby(['Category', 'State'])[['Backers', 'Usd Pledged Real']].sum().reset_index()

# Sort the entire DataFrame by 'Usd Pledged Real' in descending order
top_ten_cats = top_ten_cats.sort_values(by='Usd Pledged Real', ascending=False)

top_ten_cats.head()

In [ ]:
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter

# 1. Top 10 Categories by Total Pledged Amount
plt.figure(figsize=(10, 6))
top_pledged = top_ten_cats.groupby('Category')['Usd Pledged Real'].sum().nlargest(10)

# Highlight the highest value in blue, others in light grey
colors = ['blue' if i == 0 else 'lightgrey' for i in range(len(top_pledged))]

plt.bar(top_pledged.index, top_pledged.values, color=colors)

# Add value only on the blue bar (the highest one)
plt.text(0, top_pledged.values[0], f'{top_pledged.values[0]:,.0f}', 
         ha='center', va='bottom', fontsize=12, color='black')

# Formatting for x-axis labels and title
plt.xticks(rotation=45, ha='right')
plt.title('Top 10 Categories by Total Pledged Amount')
plt.xlabel('Category')
plt.ylabel('Total Pledged Amount (USD)')

# Add comma formatting for y-axis
plt.gca().yaxis.set_major_formatter(FuncFormatter(lambda x, _: f'{x:,.0f}'))
plt.tight_layout()
plt.show()

# 2. Top 10 Categories by Number of Backers
plt.figure(figsize=(10, 6))
top_backers = top_ten_cats.groupby('Category')['Backers'].sum().nlargest(10)

# Highlight the highest value in blue, others in light grey
colors = ['blue' if i == 0 else 'lightgrey' for i in range(len(top_backers))]

plt.bar(top_backers.index, top_backers.values, color=colors)

# Add value only on the blue bar (the highest one)
plt.text(0, top_backers.values[0], f'{top_backers.values[0]:,.0f}', 
         ha='center', va='bottom', fontsize=12, color='black')

# Formatting for x-axis labels and title
plt.xticks(rotation=45, ha='right')
plt.title('Top 10 Categories by Number of Backers')
plt.xlabel('Category')
plt.ylabel('Number of Backers')

# Add comma formatting for y-axis
plt.gca().yaxis.set_major_formatter(FuncFormatter(lambda x, _: f'{x:,.0f}'))
plt.tight_layout()
plt.show()